### ISSUE TITLE
Issues launching server using docker

### ISSUE THREAD

**Issue by aadak99** [Phyremaster/easy-gmod-docker#1]
Hello,

I was experimenting with docker to get a server up and running for garrys mod.
I found your easy-gmod solution  and followed the directions, yet I keep running into an issue which prevents from successfully launching the server. 

` docker run -e HOSTNAME="Test Branch" -e LOGINTOKEN="" -p 27015:27015/udp -p 27005:27005/udp -v gmod://Users\aadak\gmod-server\easy-gmod\garrysmod -v garrysmod:/home/steam/garrysmod --name gmod_server phyremaster/easy-gmod
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 57,746 KB)...
[  0%] Downloading update (3,077 of 57,746 KB)...
[  5%] Downloading update (6,914 of 57,746 KB)...
[ 11%] Downloading update (9,790 of 57,746 KB)...
[ 96%] Downloading update (56,848 of 57,746 KB)...
[ 98%] Downloading update (57,746 of 57,746 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1685487853
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.88 (35651584 / 4071132502)
 Update state (0x61) downloading, progress: 3.35 (136370915 / 4071132502)
 Update state (0x61) downloading, progress: 92.91 (3782423580 / 4071132502)
 Update state (0x61) downloading, progress: 100.00 (4071132502 / 4071132502)
 Update state (0x81) verifying update, progress: 14.27 (580860536 / 4071132502)
 Update state (0x81) verifying update, progress: 72.09 (2934930886 / 4071132502)
 Update state (0x81) verifying update, progress: 86.52 (3522267989 / 4071132502)
 Update state (0x101) committing, progress: 24.64 (1003231269 / 4071132502)
Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
Success! App '4020' fully installed.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1685487853
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 97.06 (2229493575 / 2297127618)
Success! App '232330' fully installed.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1685487853
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.00 (0 / 9771613529)
 Update state (0x61) downloading, progress: 81.49 (7962631104 / 9771613529)
 Update state (0x61) downloading, progress: 97.94 (9569863608 / 9771613529)
 Update state (0x61) downloading, progress: 99.29 (9702231618 / 9771613529)
 Update state (0x81) verifying update, progress: 58.37 (5703237318 / 9771613529)
 Update state (0x81) verifying update, progress: 82.36 (8048178407 / 9771613529)
 Update state (0x81) verifying update, progress: 88.38 (8636044442 / 9771613529)
 Update state (0x81) verifying update, progress: 94.39 (9223359204 / 9771613529)
 Update state (0x0) unknown, progress: 0.00 (0 / 0)
Success! App '232250' fully installed.
cp: cannot create regular file '/home/steam/garrysmod/garrysmod/cfg/mount.cfg': No such file or directory
touch: cannot touch '/home/steam/garrysmod/garrysmod/cfg/server.cfg': No such file or directory
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 38: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 47: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 56: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 65: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 118: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
grep: /home/steam/garrysmod/garrysmod/cfg/server.cfg: No such file or directory
./easygmod.sh: 122: ./easygmod.sh: cannot create /home/steam/garrysmod/garrysmod/cfg/server.cfg: Directory nonexistent
./easygmod.sh: 161: exec: /home/steam/garrysmod/srcds_run: not found
`

Here are the main different method of trying to get the server up and running that I did
1. Cloned github repository, into folder called gmod-server
2. Made sure docker daemon was running, even restarting it.
3. Started up Git Bash and cd into that folder
4. Ran the docker run command as shown above
5. Waited for all downloads to complete and error pops up
I can see that the docker container and image are populating, I can also see the directors under inspect being as listed in error. My issue could stem from there being two "garrysmod/garrysmod" in the directory but non in the actual file system in docker. 

![c7bdb41eca04658dd2d998ffcca0250b](https://github.com/Phyremaster/easy-gmod/assets/127800544/59c6f9da-06bb-421c-9006-ee43de97609f)

![f68e53977fc72fea21f2b928fcfd4cac](https://github.com/Phyremaster/easy-gmod/assets/127800544/e124c599-4642-42d9-8fdf-2becd610df47)

![7c22afd1a8fc4ecf4c7d301a15a2d56a](https://github.com/Phyremaster/easy-gmod/assets/127800544/0c8f8f05-00c7-4c44-b63b-6008fdab8a1d)

![117585ca3905361bf91c4932560876c8](https://github.com/Phyremaster/easy-gmod/assets/127800544/6ef687f7-11ea-4eec-93b0-0705088e917a)

**Comment by Phyremaster** [comment]
Sorry, I haven't touched this repo in years for various reasons.

This image probably still works though. I doubt you're still awaiting a reply, but I see the issue with your command: `-v gmod://Users\aadak\gmod-server\easy-gmod\garrysmod -v garrysmod:/home/steam/garrysmod` should be `-v C:\Users\aadak\gmod-server\easy-gmod\garrysmod:/home/steam/garrysmod`.

Also, you don't have to clone the repo; Docker handles that.
